### ISSUE TITLE
Rewrite backend tests to match checklist

### ISSUE THREAD

**Issue by pipieter** [SELab-2/Dr-Trottoir-3#201]
I've written a checklist for backend tests that each view's test file has to match for it to be properly tested. Some of the test files don't meet the requirements or can be refactored to be easier to read or navigate through. I'll be going over them one-by-one and make changes/corrections where I think they are needed. See branch [pimpieters/rewrite-backend-tests](https://github.com/SELab-2/Dr-Trottoir-3/tree/pimpieters/rewrite-backend-tests)

- [x] Building
- [ ] Garbage Collection Schedule Template Entry
- [ ] Garbage Collection Schedule Template
- [ ] Garbage Collection Schedule
- [ ] Garbage Type
- [ ] Issue Image
- [ ] Issue Detail
- [x] Location Group
- [ ] Schedule Assignment
- [ ] Schedule Definition
- [ ] Schedule Work Entry
- [ ] User
